name: black_and_isort

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - uses: psf/black@stable
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install flake8
          pip install isort
          

      - name: Lint with isort
        run: |
          isort -c .
          
      - name: Lint with black
        run: |
          black --check .
